# Generated by Django 3.1.3 on 2020-12-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tw_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=250)),
                ('create_at', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tw_tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tweet_id', models.IntegerField(default=None, null=True)),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=250)),
                ('image_path', models.CharField(max_length=250, null=True)),
                ('create_at', models.DateTimeField(verbose_name='created at')),
            ],
        ),
    ]
